name: Depoly Terraform ITG

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target environment itg'
        default: 'itg'
        required: true
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: ${{ github.event.inputs.target_environment }}
    env:
      TF_VAR_api_key_front_value: ${{ secrets.TF_VAR_API_KEY_FRONT_VALUE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: 'actions/checkout@v4'
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "${{ vars.GCP_SERVICE_ACCOUNT }}"
          
          export_environment_variables: true
          create_credentials_file: true
          access_token_lifetime: 500
          
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 416.0.0"

      - name: Check currently authenticated user
        run: gcloud auth list

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
  
      - name: Terraform Plan
        id: plan
        run: |
          terraform init -input=false -backend-config=environment/${{ github.event.inputs.target_environment }}/gcp_bucket.tfvars -reconfigure
          terraform plan -var-file=environment/${{ github.event.inputs.target_environment }}/variables.tfvars -input=false -out=${{ github.event.inputs.target_environment }}.tfplan
          terraform show --json ${{ github.event.inputs.target_environment }}.tfplan > ${{ github.event.inputs.target_environment }}-tfplan.json

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./${{ github.event.inputs.target_environment }}.tfplan
          retention-days: 1 

  terraform-apply:
    needs: terraform-plan
    name: Terraform Apply ITG
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: ${{ github.event.inputs.target_environment }}-apply

    steps:
      - uses: 'actions/checkout@v4'
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "${{ vars.GCP_SERVICE_ACCOUNT }}"
          
          export_environment_variables: true
          create_credentials_file: true
          access_token_lifetime: 500
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 416.0.0"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v5
        with:
          name: terraform-plan
          path: . 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          
      - name: Terraform Apply
        id: apply
        run: |
          terraform init -input=false -backend-config=environment/${{ github.event.inputs.target_environment }}/gcp_bucket.tfvars -reconfigure    
          terraform apply -input=false ${{ github.event.inputs.target_environment }}.tfplan
