name: Depoly Terraform DEV

on:
  push:
    branches:
      - 'main'
jobs:
  terraform-plan:
    name: Terraform Plan Dev
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: dev
    env:
      TF_VAR_api_key_front_value: ${{ secrets.TF_VAR_API_KEY_FRONT_VALUE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: 'actions/checkout@v4'
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "${{ vars.GCP_SERVICE_ACCOUNT }}"
          
          export_environment_variables: true
          create_credentials_file: true
          access_token_lifetime: 500
          
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 416.0.0"

      - name: Check currently authenticated user
        run: gcloud auth list

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
  
      - name: Terraform Plan
        id: plan
        run: |
          terraform init -input=false -backend-config=environment/dev/gcp_bucket.tfvars -reconfigure
          terraform plan -var-file=environment/dev/variables.tfvars -input=false -out=dev.tfplan
          terraform show --json dev.tfplan > dev-tfplan.json

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./dev.tfplan
          retention-days: 1 

  terraform-apply:
    name: Terraform Apply Dev
    needs: terraform-plan
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: 'write'
      repository-projects: write
    environment: dev-apply

    steps:
      - uses: 'actions/checkout@v4'
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "${{ vars.GCP_SERVICE_ACCOUNT }}"
          
          export_environment_variables: true
          create_credentials_file: true
          access_token_lifetime: 500
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 416.0.0"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v5
        with:
          name: terraform-plan
          path: . 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          
      - name: Terraform Apply
        id: apply
        run: |
          terraform init -input=false -backend-config=environment/dev/gcp_bucket.tfvars -reconfigure    
          terraform apply -input=false dev.tfplan

      - name: Trigger Release Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: terraform_apply_completed
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

